force-app/main/default/objects/Call_Log__c/Call_Log__c.object-meta.xml
<CustomObject>
    <description>Custom object for entering call logs where the notes will be tested by Einstein Language.</description>
    <label>Call Log</label>
    <nameField>
        <displayFormat>CL{0000}</displayFormat>
        <label>Call Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Log__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <inlineHelpText>Please enter the notes for your extremely important call with the customer.</inlineHelpText>
    <label>Notes</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Entity__c/Entity__c.object-meta.xml
<CustomObject>
    <description>List of entities found by Einstein NER</description>
    <label>Entity</label>
    <nameField>
        <displayFormat>NE{0000}</displayFormat>
        <label>Entity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Entity__c/fields/Call_Log__c.field-meta.xml
<CustomField>
    <fullName>Call_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Linked Call Log</inlineHelpText>
    <label>Call Log</label>
    <referenceTo>Call_Log__c</referenceTo>
    <relationshipLabel>Entities</relationshipLabel>
    <relationshipName>Entities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entity__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <inlineHelpText>Entity identified</inlineHelpText>
    <label>Entity</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entity__c/fields/Probability__c.field-meta.xml
<CustomField>
    <fullName>Probability__c</fullName>
    <inlineHelpText>Probability Score calculated by Einstein NER</inlineHelpText>
    <label>Probability</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Entity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Entity Type Identified</inlineHelpText>
    <label>Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EinsteinNERTester.cls
public class EinsteinNERTester {

    //Define constants
    static final Double cdMINIMUM_PROBABILITY = .7D;
    static final String csNER_MODEL = 'NER7';

    //Function to post the results to a related object
//	@InvocableMethod(label='Insert NER Entities' description='Insert NER Entities found in Call Log Notes.')
    public static List<Entity__c> InsertNEREntities( List<Call_Log__c> callLogs ) {

        //Define variables for me.
        String sCallLogID = callLogs[0].Id;
        List<einsteinplay.Einstein_Probability> probabilities = Predict( callLogs[0].Notes__c );

        //Cycle through each record
        for ( Integer i = 0; i < probabilities.size(); i++ ) {

            //Add a new entity
            Entity__c entity = new Entity__c();

            //Set the value
            entity.Call_Log__c = sCallLogID;
            entity.Type__c = probabilities[i].label;
            entity.Probability__c = (probabilities[i].probability * 100);
            entity.Entity__c = probabilities[i].token;

	        //Insert the records
			Database.SaveResult result = Database.insert(entity);

        }

        //Return the results
        List<Entity__c> returnEntities = [SELECT Call_Log__c, Type__c, Probability__c, Entity__c FROM Entity__c WHERE Call_Log__c =: sCallLogID];
        return returnEntities;
    }


	//Function to post the results to a related object
	@future
    public static void PostResults( String sCallLogID, String sText, Double minProbabilityScore ) {

        //Define variables
        List<einsteinplay.Einstein_Probability> probabilities = Predict( sText );

        //Cycle through each record
        for ( Integer i = 0; i < probabilities.size(); i++ ) {

            //Add a new entity
            Entity__c entity = new Entity__c();

            //Set the value
            entity.Call_Log__c = sCallLogID;
            entity.Type__c = probabilities[i].label;
            entity.Probability__c = (probabilities[i].probability * 100);
            entity.Entity__c = probabilities[i].token;

	        //Insert the records
			insert entity;
        }

    }

    //Function to execute the NER Prediction Service
    private static List<einsteinplay.Einstein_Probability> Predict( string sText ) {

        //Define variables
        einsteinplay.Einstein_PredictionService service = new einsteinplay.Einstein_PredictionService(einsteinplay.Einstein_PredictionService.Types.NER);
        einsteinplay.Einstein_PredictionResult prediction = service.predictNER( csNER_MODEL, sText, 5, '');
		List<einsteinplay.Einstein_Probability> results = prediction.probabilities;

        //Test whether anything returned
        if (!results.isEmpty()) {

            //Set variables
        	System.debug( results );
			System.debug( results.size() );

        }

        //Return the results
        return results;
    }
}